# Security Configuration for OpenStack Multi-Tenant Environment
# This file defines security policies, validation rules, and compliance requirements

# Security Framework Configuration
security_framework:
  compliance_standards:
    - "NIST_CSF"
    - "ISO_27001"
    - "SOC2_TYPE_II"
    - "PCI_DSS"
    - "GDPR"
  
  risk_tolerance: "LOW"  # LOW, MEDIUM, HIGH
  security_level: "STRICT"  # BASIC, STANDARD, STRICT

# OpenStack Service Configuration
openstack:
  auth_url: "https://keystone.openstack.local:5000/v3"
  region: "RegionOne"
  services:
    - name: "keystone"
      port: 5000
      ssl_required: true
      min_tls_version: "1.3"
    - name: "nova"
      port: 8774
      ssl_required: true
      min_tls_version: "1.3"
    - name: "neutron"
      port: 9696
      ssl_required: true
      min_tls_version: "1.3"
    - name: "cinder"
      port: 8776
      ssl_required: true
      min_tls_version: "1.3"
    - name: "glance"
      port: 9292
      ssl_required: true
      min_tls_version: "1.3"

# Security Validation Rules
validation_rules:
  # Credential Security
  credentials:
    no_hardcoded_passwords: true
    vault_encryption_required: true
    password_complexity:
      min_length: 14
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special_chars: true
      forbidden_patterns:
        - "password"
        - "123456"
        - "admin"
        - "default"
  
  # Network Security
  network:
    default_deny_policy: true
    restrict_ssh_access: true
    api_network_isolation: true
    no_public_database_access: true
    firewall_required: true
    ddos_protection: true
    
  # TLS/SSL Security
  tls:
    min_version: "1.3"
    max_version: "1.3"
    required_ciphers:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    forbidden_ciphers:
      - "RC4"
      - "MD5"
      - "SHA1"
      - "3DES"
    certificate_validation: true
    hsts_required: true
    
  # File Security
  file_permissions:
    sensitive_files:
      - path: "/etc/keystone/keystone.conf"
        max_permissions: "0600"
        owner: "keystone"
      - path: "/etc/nova/nova.conf"
        max_permissions: "0600"
        owner: "nova"
      - path: "/etc/ssl/private/*"
        max_permissions: "0600"
        owner: "root"
      - path: "/home/*/.ssh/id_*"
        max_permissions: "0600"
    no_world_writable: true
    no_suid_files: true
    
  # Authentication Security
  authentication:
    disable_root_login: true
    disable_password_auth: true
    max_auth_tries: 3
    session_timeout: 900  # 15 minutes
    lockout_threshold: 5
    lockout_duration: 1800  # 30 minutes
    
  # API Security
  api:
    rate_limiting: true
    max_requests_per_minute: 100
    max_requests_per_hour: 1000
    request_timeout: 30
    max_request_size: "1MB"
    security_headers_required: true
    cors_disabled: true
    
  # Audit and Logging
  audit:
    retention_days_min: 2555  # 7 years
    real_time_monitoring: true
    log_integrity: true
    centralized_logging: true
    siem_integration: true

# Security Scanning Configuration
scanning:
  vulnerability_scanning:
    enabled: true
    schedule: "daily"
    tools:
      - "nmap"
      - "openvas"
      - "trivy"
      - "clair"
    severity_threshold: "MEDIUM"
    
  credential_scanning:
    enabled: true
    patterns:
      - "password\\s*=\\s*[\"']?[^\"'\\s]+[\"']?"
      - "secret\\s*=\\s*[\"']?[^\"'\\s]+[\"']?"
      - "token\\s*=\\s*[\"']?[^\"'\\s]+[\"']?"
      - "key\\s*=\\s*[\"']?[^\"'\\s]+[\"']?"
      - "admin.*=.*[\"']?[^\"'\\s]+[\"']?"
    exclude_patterns:
      - "{{.*}}"  # Ansible templates
      - "${.*}"   # Environment variables
      
  malware_scanning:
    enabled: true
    schedule: "daily"
    quarantine_suspicious: true
    
  image_scanning:
    enabled: true
    scan_on_upload: true
    policy: "strict"
    vulnerability_database: "trivy"

# Incident Response Configuration
incident_response:
  automated_response:
    enabled: true
    actions:
      - type: "block_ip"
        trigger: "brute_force_attempt"
        duration: 3600
      - type: "disable_account"
        trigger: "repeated_failures"
        threshold: 5
      - type: "alert_admin"
        trigger: "privilege_escalation"
        urgency: "HIGH"
        
  notification_channels:
    - type: "email"
      recipients: ["security@company.com", "admin@company.com"]
      severity_threshold: "MEDIUM"
    - type: "slack"
      webhook: "{{ vault_slack_security_webhook }}"
      severity_threshold: "HIGH"
    - type: "sms"
      recipients: ["+1234567890"]
      severity_threshold: "CRITICAL"

# Compliance Monitoring
compliance:
  pci_dss:
    enabled: false  # Enable if processing credit cards
    requirements:
      - "install_maintain_firewall"
      - "no_default_passwords"
      - "protect_cardholder_data"
      - "encrypt_transmission"
      - "use_maintain_antivirus"
      - "secure_systems_applications"
      
  sox:
    enabled: false  # Enable for financial data
    requirements:
      - "access_controls"
      - "audit_trails"
      - "data_integrity"
      - "change_management"
      
  hipaa:
    enabled: false  # Enable for healthcare data
    requirements:
      - "access_control"
      - "audit_controls"
      - "integrity"
      - "person_authentication"
      - "transmission_security"

# Security Metrics and KPIs
metrics:
  security_score:
    target: 95
    weight_factors:
      critical_vulnerabilities: 0.4
      high_vulnerabilities: 0.3
      medium_vulnerabilities: 0.2
      low_vulnerabilities: 0.1
      
  sla_targets:
    vulnerability_remediation:
      critical: 4  # hours
      high: 24     # hours
      medium: 168  # hours (1 week)
      low: 720     # hours (30 days)
      
    incident_response:
      detection: 15    # minutes
      containment: 60  # minutes
      recovery: 240    # minutes
      
  reporting:
    frequency: "weekly"
    recipients: ["security@company.com", "management@company.com"]
    format: ["pdf", "json"]

# Security Testing Configuration
testing:
  penetration_testing:
    schedule: "quarterly"
    scope: ["network", "application", "social_engineering"]
    external_vendor: true
    
  red_team_exercises:
    schedule: "annually"
    duration: "1_week"
    scope: "full_infrastructure"
    
  security_awareness:
    phishing_simulation: "monthly"
    training_frequency: "quarterly"
    compliance_tracking: true

# Backup Security Configuration
backup_security:
  encryption_required: true
  encryption_algorithm: "AES-256-GCM"
  key_rotation_interval: "30d"
  offsite_storage: true
  access_logging: true
  integrity_checking: true
  
# Disaster Recovery Security
disaster_recovery:
  security_validation: true
  access_controls_preserved: true
  audit_trail_maintained: true
  communication_security: true
